### ISSUE TITLE
Revisión Campos PLantilla

### ISSUE THREAD

**Issue by jorgecar0** [cm45t3r/gaceta#10]
# Validación de campos del Formulario Gaceta

## Tipo de incidencia
- [ ] Regresión
- [x] Reporte de falla
- [ ] Nueva funcionalidad
- [ ] Error en documentación

## Comportamiento actual
Descripción breve de la anomalía.

[PRUEBAS gaceta Dic-2018.docx](https://github.com/cm45t3r/gaceta/files/2664960/PRUEBAS.gaceta.Dic-2018.docx)
Validación de campos del formulario

## Comportamiento esperado
Descripción breve del comportamiento adecuado del sistema para el caso de uso específico.

Se validaron los campos del formulario y se detectaron errores en varios campos.
No. documento  y No. Expediente

## Instrucciones de reproducción
1. Se adjunta archivo Word con el detalle de los errores identificados.

## Caso de uso
Caso de uso o justificación de la incidencia.

## Ambiente
**Versión:** 1.0

**Browser:**
- [x] Todos
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] IE 11
- [ ] Edge

**OS:**
- [ ] Todos
- [ ] Android
- [ ] iOS
- [x] Windows 10
- [ ] Linux/Unix

**Comment by cm45t3r** [comment]
Se da solución a la incidencia. Por favor realizar las pruebas correspondientes.

**Comment by cm45t3r** [comment]
Resuelto
